# Generated by Django 5.1.6 on 2025-02-10 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaioX',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pd_direito_cima', models.ImageField(upload_to='imagens/raiox/<django.db.models.fields.UUIDField>')),
                ('pd_direito_lateral', models.ImageField(upload_to='imagens/raiox/<django.db.models.fields.UUIDField>')),
                ('pe_esquerdo_cima', models.ImageField(upload_to='imagens/raiox/<django.db.models.fields.UUIDField>')),
                ('pe_esquerdo_lateral', models.ImageField(upload_to='imagens/raiox/<django.db.models.fields.UUIDField>')),
                ('ambos_cima', models.ImageField(upload_to='imagens/raiox/<django.db.models.fields.UUIDField>')),
            ],
        ),
        migrations.CreateModel(
            name='Ressonancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pd_direito_cima', models.ImageField(upload_to='imagens/ressonancia/<django.db.models.fields.UUIDField>')),
                ('pd_direito_lateral', models.ImageField(upload_to='imagens/ressonancia/<django.db.models.fields.UUIDField>')),
                ('pe_esquerdo_cima', models.ImageField(upload_to='imagens/ressonancia/<django.db.models.fields.UUIDField>')),
                ('pe_esquerdo_lateral', models.ImageField(upload_to='imagens/ressonancia/<django.db.models.fields.UUIDField>')),
                ('ambos_cima', models.ImageField(upload_to='imagens/ressonancia/<django.db.models.fields.UUIDField>')),
            ],
        ),
        migrations.CreateModel(
            name='MultiModal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('raio_x', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal', to='web.raiox')),
                ('ressonancia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal', to='web.ressonancia')),
            ],
        ),
    ]
