# Generated by Django 5.1.6 on 2025-02-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiox',
            name='ambos_cima',
            field=models.ImageField(upload_to='imagens/raiox'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='pd_direito_cima',
            field=models.ImageField(upload_to='imagens/raiox'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='pd_direito_lateral',
            field=models.ImageField(upload_to='imagens/raiox'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='pe_esquerdo_cima',
            field=models.ImageField(upload_to='imagens/raiox'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='pe_esquerdo_lateral',
            field=models.ImageField(upload_to='imagens/raiox'),
        ),
        migrations.AlterField(
            model_name='ressonancia',
            name='ambos_cima',
            field=models.ImageField(upload_to='imagens/ressonancia/'),
        ),
        migrations.AlterField(
            model_name='ressonancia',
            name='pd_direito_cima',
            field=models.ImageField(upload_to='imagens/ressonancia/'),
        ),
        migrations.AlterField(
            model_name='ressonancia',
            name='pd_direito_lateral',
            field=models.ImageField(upload_to='imagens/ressonancia/'),
        ),
        migrations.AlterField(
            model_name='ressonancia',
            name='pe_esquerdo_cima',
            field=models.ImageField(upload_to='imagens/ressonancia/'),
        ),
        migrations.AlterField(
            model_name='ressonancia',
            name='pe_esquerdo_lateral',
            field=models.ImageField(upload_to='imagens/ressonancia/'),
        ),
    ]
