# Generated by Django 5.1.6 on 2025-02-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_raiox_ambos_cima_alter_raiox_pd_direito_cima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raiox',
            old_name='ambos_cima',
            new_name='img_ambos_cima',
        ),
        migrations.RenameField(
            model_name='raiox',
            old_name='pd_direito_cima',
            new_name='img_pd_cima',
        ),
        migrations.RenameField(
            model_name='raiox',
            old_name='pd_direito_lateral',
            new_name='img_pd_lateral',
        ),
        migrations.RenameField(
            model_name='raiox',
            old_name='pe_esquerdo_cima',
            new_name='img_pe_cima',
        ),
        migrations.RenameField(
            model_name='raiox',
            old_name='pe_esquerdo_lateral',
            new_name='img_pe_lateral',
        ),
        migrations.RenameField(
            model_name='ressonancia',
            old_name='ambos_cima',
            new_name='img_ambos_cima',
        ),
        migrations.RenameField(
            model_name='ressonancia',
            old_name='pd_direito_cima',
            new_name='img_pd_cima',
        ),
        migrations.RenameField(
            model_name='ressonancia',
            old_name='pd_direito_lateral',
            new_name='img_pd_lateral',
        ),
        migrations.RenameField(
            model_name='ressonancia',
            old_name='pe_esquerdo_cima',
            new_name='img_pe_cima',
        ),
        migrations.RenameField(
            model_name='ressonancia',
            old_name='pe_esquerdo_lateral',
            new_name='img_pe_lateral',
        ),
    ]
