# Generated by Django 5.1.6 on 2025-03-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_ambos_cima_raiox_img_ambos_cima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodal',
            name='prontuario',
            field=models.FileField(default='Prontuário não informado', upload_to='prontuario'),
        ),
        migrations.AddField(
            model_name='raiox',
            name='prontuario',
            field=models.FileField(default='Prontuário não informado', upload_to='prontuario/'),
        ),
        migrations.AddField(
            model_name='ressonancia',
            name='prontuario',
            field=models.FileField(default='Prontuário não informado', upload_to='prontuario/'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='img_ambos_cima',
            field=models.ImageField(upload_to='imagens/raiox/'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='img_pd_cima',
            field=models.ImageField(upload_to='imagens/raiox/'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='img_pd_lateral',
            field=models.ImageField(upload_to='imagens/raiox/'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='img_pe_cima',
            field=models.ImageField(upload_to='imagens/raiox/'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='img_pe_lateral',
            field=models.ImageField(upload_to='imagens/raiox/'),
        ),
    ]
