# Generated by Django 5.1.6 on 2025-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_multimodal_prontuario_raiox_prontuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodal',
            name='prontuario',
            field=models.FileField(default='Prontuário não informado', upload_to='prontuario/geral'),
        ),
        migrations.AlterField(
            model_name='raiox',
            name='prontuario',
            field=models.FileField(default='Prontuário não informado', upload_to='prontuario/raiox'),
        ),
        migrations.AlterField(
            model_name='ressonancia',
            name='prontuario',
            field=models.FileField(default='Prontuário não informado', upload_to='prontuario/ressonancia'),
        ),
    ]
