# Generated by Django 5.1.6 on 2025-03-31 18:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_multimodal_prontuario_alter_raiox_prontuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressonancia',
            name='img_ambos_cima',
        ),
        migrations.RemoveField(
            model_name='ressonancia',
            name='img_pd_cima',
        ),
        migrations.RemoveField(
            model_name='ressonancia',
            name='img_pd_lateral',
        ),
        migrations.RemoveField(
            model_name='ressonancia',
            name='img_pe_cima',
        ),
        migrations.RemoveField(
            model_name='ressonancia',
            name='img_pe_lateral',
        ),
        migrations.AddField(
            model_name='ressonancia',
            name='imagens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
    ]
