# Generated by Django 5.1.6 on 2025-04-02 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_ressonancia_img_ambos_cima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensRessonancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='imagens/ressonancia')),
            ],
        ),
        migrations.RemoveField(
            model_name='ressonancia',
            name='imagens',
        ),
        migrations.AddField(
            model_name='ressonancia',
            name='imagens',
            field=models.ManyToManyField(to='web.imagensressonancia'),
        ),
    ]
