# Generated by Django 5.1.6 on 2025-04-28 18:33

import cpf_field.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_imagensressonancia_remove_ressonancia_imagens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField()),
                ('sobrenome', models.CharField()),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('crm', models.CharField(unique=True)),
                ('data_aniversario', models.DateField()),
                ('email', models.EmailField(error_messages='Email inválido. Tente novamente', max_length=254)),
                ('senha', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='multimodal',
            name='raio_x',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal', to='web.raiox'),
        ),
        migrations.AlterField(
            model_name='multimodal',
            name='ressonancia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimodal', to='web.ressonancia'),
        ),
        migrations.AddField(
            model_name='multimodal',
            name='clinico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='web.clinico'),
        ),
    ]
