# Generated by Django 5.1.6 on 2025-07-24 19:22

import cpf_field.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_clinico_email_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cpf', cpf_field.models.CPFField(max_length=14, unique=True)),
                ('crm', models.CharField(max_length=50, unique=True)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cpf', cpf_field.models.CPFField(max_length=14)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resonance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record', models.FileField(blank=True, null=True, upload_to='exams/%Y/%m/%d/records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record', models.FileField(blank=True, null=True, upload_to='exams/%Y/%m/%d/records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='multimodal',
            name='clinico',
        ),
        migrations.RemoveField(
            model_name='ressonancia',
            name='imagens',
        ),
        migrations.RemoveField(
            model_name='multimodal',
            name='raio_x',
        ),
        migrations.RemoveField(
            model_name='multimodal',
            name='ressonancia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='exame',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('2D', '2D'), ('3D', '3D')], max_length=3)),
                ('record', models.FileField(blank=True, null=True, upload_to='exams/%Y/%m/%d/records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='web.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='web.patient')),
                ('resonance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='web.resonance')),
                ('xray', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='web.xray')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.FileField(blank=True, null=True, upload_to='exams/results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='web.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesResonance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='exams/resonance/images')),
                ('resonance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.resonance')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesXRay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='exams/xray/images')),
                ('xray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.xray')),
            ],
        ),
        migrations.DeleteModel(
            name='Clinico',
        ),
        migrations.DeleteModel(
            name='ImagensRessonancia',
        ),
        migrations.DeleteModel(
            name='RaioX',
        ),
        migrations.DeleteModel(
            name='Ressonancia',
        ),
        migrations.DeleteModel(
            name='MultiModal',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
